In [17]:
## Data Quality Checks
## Order_items Table

In [153]:
#1 shape check
import pandas as pd

order_items = pd.read_csv("C:\\Users\\HAMAHANG\\OneDrive\\Desktop\\Data Analysis\\End to end projects\\Brazilian E-commerce\\00_raw_data\\olist_order_items_dataset.csv")
display(order_items.shape)
display(order_items.dtypes)
display(order_items.head())

(112650, 7)

order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [156]:
#changing dtype of timestamp from str to date type
order_items["shipping_limit_date"] = pd.to_datetime(order_items["shipping_limit_date"])

In [157]:
#2 missing values
order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [159]:
#3 duplicate check
order_items.duplicated().sum()

np.int64(0)

In [188]:
#unique PK check
order_items.duplicated(subset=["order_id", "order_item_id"]).sum()

np.int64(0)

In [186]:
#4 logic check - price & fleight value value-check
order_items[["price", "freight_value"]].describe()

               price  freight_value
count  112650.000000  112650.000000
mean      120.653739      19.990320
std       183.633928      15.806405
min         0.850000       0.000000
25%        39.900000      13.080000
50%        74.990000      16.260000
75%       134.900000      21.150000
max      6735.000000     409.680000

In [181]:
(order_items["freight_value"] == 0).sum()

np.int64(383)

In [183]:
'''
freight value = 0, can be intentional
'''

In [179]:
(order_items["price"] <= 0).sum()

np.int64(0)

In [180]:
(order_items["freight_value"] < 0).sum()

np.int64(0)

In [4]:
## Customers Table
#1: shape check

customers = pd.read_csv("C:\\Users\\HAMAHANG\\OneDrive\\Desktop\\Data Analysis\\End to end projects\\Brazilian E-commerce\\00_raw_data\\olist_customers_dataset.csv")
display(customers.shape)
display(customers.dtypes)
display(customers.head())

(99441, 5)

customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [7]:
#since int dtype may include 0 at the start, dtype for zip_code is changed into str
customers["customer_zip_code_prefix"] = customers["customer_zip_code_prefix"].astype(str)
display(customers.dtypes)

customer_id                 object
customer_unique_id          object
customer_zip_code_prefix    object
customer_city               object
customer_state              object
dtype: object

In [30]:
#2:missing value check
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [32]:
#3:DUPLICATE CHECKS (KEY VALIDATION)
customers.duplicated().sum()

np.int64(0)

In [33]:
#unique PK
customers["customer_id"].duplicated().sum()

np.int64(0)

In [10]:
#4:VALUE SANITY CHECKS
customers_test_a = customers["customer_state"].value_counts().head()
customers_test_b = customers["customer_zip_code_prefix"].astype(str).str.len().value_counts()

In [12]:
display(customers_test_a)
display(customers_test_b)

customer_state
SP    41746
RJ    12852
MG    11635
RS     5466
PR     5045
Name: count, dtype: int64

customer_zip_code_prefix
5    75446
4    23995
Name: count, dtype: int64

In [40]:
#count of unique customers
customers["customer_unique_id"].nunique()

96096

In [ ]:
## Orders Table
#1: shape check

In [18]:
orders = pd.read_csv("C:\\Users\\HAMAHANG\\OneDrive\\Desktop\\Data Analysis\\End to end projects\\Brazilian E-commerce\\00_raw_data\\olist_orders_dataset.csv")
display(orders.shape)
display(orders.dtypes)
display(orders.head())

(99441, 8)

order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [54]:
#converting dtypes for timestamp columns
orders["order_purchase_timestamp"] = pd.to_datetime(orders["order_purchase_timestamp"])
orders["order_approved_at"] = pd.to_datetime(orders["order_approved_at"])
orders["order_delivered_carrier_date"] = pd.to_datetime(orders["order_delivered_carrier_date"])
orders["order_delivered_customer_date"] = pd.to_datetime(orders["order_delivered_customer_date"])
orders["order_estimated_delivery_date"] = pd.to_datetime(orders["order_estimated_delivery_date"])
display(orders.dtypes)

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [56]:
#2:missing value check
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [58]:
#the missing values could be the result of orders not completed and be part of the business process. but if a 'delivered' order is missing, that is missing data:
orders[
    (orders["order_status"] == "delivered") &
    (orders["order_delivered_customer_date"].isnull())
]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,ec05a6d8558c6455f0cbbd8a420ad34f,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,2017-11-30 18:12:23,NaT,2017-12-18
20618,f5dd62b788049ad9fc0526e3ad11a097,5e89028e024b381dc84a13a3570decb4,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,2018-06-25 08:05:00,NaT,2018-07-16
43834,2ebdfc4f15f23b91474edf87475f108e,29f0540231702fda0cfdee0a310f11aa,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,2018-07-03 13:57:00,NaT,2018-07-30
79263,e69f75a717d64fc5ecdfae42b2e8e086,cfda40ca8dd0a5d486a9635b611b398a,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,2018-07-03 13:57:00,NaT,2018-07-30
82868,0d3268bad9b086af767785e3f0fc0133,4f1d63d35fb7c8999853b2699f5c7649,delivered,2018-07-01 21:14:02,2018-07-01 21:29:54,2018-07-03 09:28:00,NaT,2018-07-24
92643,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaT,NaT,2017-06-23
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,dd1b84a7286eb4524d52af4256c0ba24,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,2018-06-12 14:10:00,NaT,2018-06-26
98038,20edc82cf5400ce95e1afacc25798b31,28c37425f1127d887d7337f284080a0f,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,2018-07-03 19:26:00,NaT,2018-07-19

In [ ]:
# 8 orders marked as delivered have missing delivery timestamps. Share is extremely small (<0.01%), likely minor logging errors.
#Rows retained but should be careful with them for delivery-time or such calculations.

In [60]:
#3:DUPLICATE CHECKS (KEY VALIDATION)
orders.duplicated().sum()

np.int64(0)

In [31]:
#unique PK
orders["order_id"].duplicated().sum()

np.int64(0)

In [21]:
#4:VALUE SANITY CHECKS
orders["order_status"].unique()

array(['delivered', 'invoiced', 'shipped', 'processing', 'unavailable',
       'canceled', 'created', 'approved'], dtype=object)

In [19]:
#count of unique orders
orders["order_id"].nunique()

99441

In [23]:
#dates check
orders["order_purchase_timestamp"].min()

'2016-09-04 21:15:19'

In [24]:
orders["order_purchase_timestamp"].max()

'2018-10-17 17:30:18'

In [26]:
#purchase date before approve date
(orders["order_approved_at"] < orders["order_purchase_timestamp"]).sum()

np.int64(0)

In [27]:
(orders["order_delivered_customer_date"] < orders["order_purchase_timestamp"]).sum()

np.int64(0)

In [38]:
## Geo_location Table
#1: shape check

geo_loc = pd.read_csv("C:\\Users\\HAMAHANG\\OneDrive\\Desktop\\Data Analysis\\End to end projects\\Brazilian E-commerce\\00_raw_data\\olist_geolocation_dataset.csv")
display(geo_loc.shape)
display(geo_loc.info())
display(geo_loc.head())

(1000163, 5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

None

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [67]:
#since int dtype may include 0 at the start, dtype for zip_code is changed into str
geo_loc["geolocation_zip_code_prefix"] = geo_loc["geolocation_zip_code_prefix"].astype(str)
display(geo_loc.dtypes)

geolocation_zip_code_prefix     object
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object

In [30]:
#2:missing value check
geo_loc.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [32]:
#3:DUPLICATE CHECKS (KEY VALIDATION)
geo_loc.duplicated().sum()

np.int64(261831)

In [34]:
#4 Sanity checks - unique count
geo_loc["geolocation_zip_code_prefix"].nunique()

19015

In [40]:
# distribution of rows per prefix
geo_loc["geolocation_zip_code_prefix"].value_counts().head(10)

geolocation_zip_code_prefix
24220    1146
24230    1102
38400     965
35500     907
11680     879
22631     832
30140     810
11740     788
38408     773
28970     743
Name: count, dtype: int64

In [54]:
# coordinate range sanity - lat between -34, 6
Brazil_lat = geo_loc["geolocation_lat"].min(), geo_loc["geolocation_lat"].max()
display(Brazil_lat)

(-36.6053744107061, 45.06593318269697)

In [55]:
# coordinate range sanity - lng between -75, -30
Brazil_lng = geo_loc["geolocation_lng"].min(), geo_loc["geolocation_lng"].max()
display(Brazil_lng)

(-101.46676644931476, 121.10539381057764)

In [66]:
#the range of lat & lng is outside Brazil. First we check if they are just outliers or not, if percentage is low we ignore.

# 1. Define the mask for outliers
outlier_mask = (
    (geo_loc["geolocation_lat"] < -37) | (geo_loc["geolocation_lat"] > 5) |
    (geo_loc["geolocation_lng"] < -75) | (geo_loc["geolocation_lng"] > -30)
)

# 2. Count them
outlier_count = outlier_mask.sum()

# 3. Calculate percentage
outlier_pct = (outlier_count / len(geo_loc)) * 100

print(f"Total outlier rows: {outlier_count}")
print(f"Percentage of total data: {outlier_pct:.4f}%")

Total outlier rows: 26
Percentage of total data: 0.0026%

In [71]:
geo_loc[["geolocation_city", "geolocation_state"]].value_counts().head()

geolocation_city  geolocation_state
sao paulo         SP                   135799
rio de janeiro    RJ                    62149
belo horizonte    MG                    27805
são paulo         SP                    24917
curitiba          PR                    16593
Name: count, dtype: int64

In [ ]:
# geolocation_city contains Portuguese/local spellings with accents and possible normalization inconsistencies;
#if city-level analysis is needed later, text standardization may be required.

In [72]:
## Order Payments Table
#1: shape check

order_payments = pd.read_csv("C:\\Users\\HAMAHANG\\OneDrive\\Desktop\\Data Analysis\\End to end projects\\Brazilian E-commerce\\00_raw_data\\olist_order_payments_dataset.csv")
display(order_payments.shape)
display(order_payments.info())
display(order_payments.head())

(103886, 5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

None

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [73]:
#2:missing value check
order_payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [74]:
#3:DUPLICATE CHECKS (KEY VALIDATION)
order_payments.duplicated().sum()

np.int64(0)

In [75]:
#unique PK
order_payments[["order_id", "payment_sequential"]].duplicated().sum()

np.int64(0)

In [80]:
#4 Sanity checks - unique count
order_payments[["order_id", "payment_sequential", "payment_installments" , "payment_type"]].nunique()

order_id                99440
payment_sequential         29
payment_installments       24
payment_type                5
dtype: int64

In [81]:
order_payments["payment_value"].describe()

count    103886.000000
mean        154.100380
std         217.494064
min           0.000000
25%          56.790000
50%         100.000000
75%         171.837500
max       13664.080000
Name: payment_value, dtype: float64

In [83]:
#min = 0 seems sus. Based on AI info, if it is from, like a voucher it should be ok.
order_payments.loc[order_payments["payment_value"] == 0, "payment_type"].value_counts()

payment_type
voucher        6
not_defined    3
Name: count, dtype: int64

In [84]:
# Order Review Table
#1: shape check

order_reviews = pd.read_csv("C:\\Users\\HAMAHANG\\OneDrive\\Desktop\\Data Analysis\\End to end projects\\Brazilian E-commerce\\00_raw_data\\olist_order_reviews_dataset.csv")
display(order_reviews.shape)
display(order_reviews.info())
display(order_reviews.head())

(99224, 7)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

None

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [85]:
order_reviews["review_creation_date"] = pd.to_datetime(order_reviews["review_creation_date"])
order_reviews["review_answer_timestamp"] = pd.to_datetime(order_reviews["review_answer_timestamp"])
display(order_reviews.dtypes)

review_id                          object
order_id                           object
review_score                        int64
review_comment_title               object
review_comment_message             object
review_creation_date       datetime64[ns]
review_answer_timestamp    datetime64[ns]
dtype: object

In [88]:
#2 missing values
order_reviews.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [90]:
#3:DUPLICATE CHECKS (KEY VALIDATION)
order_reviews.duplicated().sum()

np.int64(0)

In [93]:
#unique PK
order_reviews[["review_id", "order_id"]].duplicated().sum()

np.int64(0)

In [98]:
#4 Logic test - only 1 to 5 allowed
order_reviews["review_score"].value_counts().sort_index()

review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

In [121]:
## Products Table
products = pd.read_csv("C:\\Users\\HAMAHANG\\OneDrive\\Desktop\\Data Analysis\\End to end projects\\Brazilian E-commerce\\00_raw_data\\olist_products_dataset.csv")
display(products.shape)
display(products.info())
display(products.head())

(32951, 9)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

None

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [103]:
#2 missing values
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [ ]:
'''
610 products (≈1.85%) are missing product_category_name and related metadata fields.
This represents a small proportion of the catalog and is unlikely to materially affect category-level analysis.
These rows will be excluded or labeled as “unknown” in category-based analyses if needed.
'''

In [107]:
#3:DUPLICATE CHECKS (KEY VALIDATION)
products.duplicated().sum()

np.int64(0)

In [110]:
#Unique PK
products["product_id"].duplicated().sum()

np.int64(0)

In [116]:
#4 Logic $ Sanity checks - negative values
invalid_cols = products[["product_name_lenght",
                       "product_photos_qty",
                       "product_weight_g",
                       "product_length_cm",
                       "product_height_cm",
                       "product_width_cm"]] < 0
invalid_cols.sum()

product_name_lenght    0
product_photos_qty     0
product_weight_g       0
product_length_cm      0
product_height_cm      0
product_width_cm       0
dtype: int64

In [122]:
#logical values check
exclude = products[["product_id", "product_category_name"]]
temp_products = products[[col for col in products.columns if col not in exclude]].describe()
display(temp_products)

,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32341.000000,32341.000000,32341.000000,32949.000000,32949.000000,32949.000000,32949.000000
mean,48.476949,771.495285,2.188986,2276.472488,30.815078,16.937661,23.196728
std,10.245741,635.115225,1.736766,4282.038731,16.914458,13.637554,12.079047
min,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,42.000000,339.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,51.000000,595.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,57.000000,972.000000,3.000000,1900.000000,38.000000,21.000000,30.000000
max,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

In [123]:
#min = 0 in prodcut weight is odd
(products["product_weight_g"] == 0).sum()

np.int64(4)

In [ ]:
'''
extremely minor, could be missing values, could be super low weight. ignorable
'''

In [127]:
## Sellers Table
#1: shape check

sellers = pd.read_csv("C:\\Users\\HAMAHANG\\OneDrive\\Desktop\\Data Analysis\\End to end projects\\Brazilian E-commerce\\00_raw_data\\olist_sellers_dataset.csv")
display(sellers.shape)
display(sellers.info())
display(sellers.head())

(3095, 4)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

None

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [133]:
#change zip_code into str
sellers["seller_zip_code_prefix"] = sellers["seller_zip_code_prefix"].astype(str)

In [134]:
#2 missing values
sellers.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [136]:
#3 duplicates
sellers.duplicated().sum()

np.int64(0)

In [140]:
#4 Logic check - zipcode check
sellers["seller_zip_code_prefix"].astype(str).str.len().value_counts()

seller_zip_code_prefix
5    2068
4    1027
Name: count, dtype: int64

In [141]:
#seller state only 2 CAP LETTERS
sellers["seller_state"].astype(str).str.len().value_counts()

seller_state
2    3095
Name: count, dtype: int64

In [142]:
#seller city length
sellers["seller_city"].astype(str).str.len().value_counts()

seller_city
9     909
8     481
7     318
14    273
6     169
10    141
11    135
12     98
21     91
5      90
13     83
15     63
19     50
18     43
20     32
4      29
16     24
3      17
17     17
23      9
25      6
22      6
2       4
30      2
24      1
40      1
31      1
26      1
38      1
Name: count, dtype: int64

In [163]:
city_check = sellers[sellers["seller_city"].str.len() == 2]
display(city_check)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
1117,16bdc8cefd0e32a6f0824d296c5ad14a,12903,sp,SP
1246,2156f2671501a81034d7d07f217609d0,4776,sp,SP
1889,1de62b6f2fd96227629786db492433db,16021,sp,SP
2536,0b18d63d0cd1d723567903fd34a07df2,5141,sp,SP

In [ ]:
'''
city names might need some cleaning and normalisation for consistancy(both sp and sao paulo in city names is mis-informing)
'''

In [148]:
#product_category_name_translation
#1: shape check

cat_eng = pd.read_csv("C:\\Users\\HAMAHANG\\OneDrive\\Desktop\\Data Analysis\\End to end projects\\Brazilian E-commerce\\00_raw_data\\product_category_name_translation.csv")
display(cat_eng.shape)
display(cat_eng.info())
display(cat_eng.head())

(71, 2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

None

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [149]:
#2 missing values
cat_eng.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [150]:
#3 duplicate check
cat_eng.duplicated().sum()

np.int64(0)

In [189]:
#Referential Integrity Checks
orders["customer_id"].isin(customers["customer_id"]).all()

np.True_

In [190]:
order_items["order_id"].isin(orders["order_id"]).all()

np.True_

In [191]:
order_items["product_id"].isin(products["product_id"]).all()

np.True_

In [192]:
order_items["seller_id"].isin(sellers["seller_id"]).all()

np.True_

In [194]:
products["product_category_name"].dropna().isin(
    cat_eng["product_category_name"]
).all()

np.False_

In [197]:
#check to see why the test result is false
products["product_category_name"].nunique()

73

In [198]:
cat_eng["product_category_name"].nunique()

71

In [196]:
set(products["product_category_name"].dropna()) - set(cat_eng["product_category_name"])

{'pc_gamer', 'portateis_cozinha_e_preparadores_de_alimentos'}

In [ ]:
#for relevant analysis, you can add these two in the translation table